GET http://localhost:3000/products
Content-Type: application/json

###
GET http://localhost:3000/products/65da48614be87631b7880a18
Content-Type: application/json

###
DELETE http://localhost:3000/products/65db86275139f4ba31968c83
Content-Type: application/json




###
GET http://localhost:3000/orders
Content-Type: application/json

###
POST http://localhost:3000/orders
Content-Type: application/json

{
    "productID": "65dfae0ab1ec490d02d5ae01"
}

###
GET http://localhost:3000/orders/65e0d6037c9d3f7711d4c007c
Content-Type: application/json

###
DELETE http://localhost:3000/orders/65e2344aefecb966c5fee362
Content-Type: application/json

###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "random@net.com",
    "password": "1234faba"
}

###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "tester2",
    "password": "abcdelgkj"
}

###
DELETE http://localhost:3000/user/65e77cca2c22b05d0ab07442
Content-Type: application/json