GET http://localhost:3000/products
Content-Type: application/json

###
GET http://localhost:3000/products/65da48614be87631b7880a12
Content-Type: application/json

###
DELETE http://localhost:3000/products/65f222596fb0cef38149a152
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzY2NjAxLCJleHAiOjE3MTAzNzAyMDF9.OJuOlrGdCN7dl7GQ0sE6_zwCsyu6sVh4FjpqsfKMXBo


###
POST http://localhost:3000/products
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzcwMjUxLCJleHAiOjE3MTAzNzM4NTF9.FLpTK9v5DCwNtBLZd7ola8KwJg7EVjkpfhuvoAU2srI
Content-Type: application/json

{
    "name": "test1",
    "price": 6
}



###
GET http://localhost:3000/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzcwMjUxLCJleHAiOjE3MTAzNzM4NTF9.FLpTK9v5DCwNtBLZd7ola8KwJg7EVjkpfhuvoAU2srI

###
POST http://localhost:3000/orders
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzcwMjUxLCJleHAiOjE3MTAzNzM4NTF9.FLpTK9v5DCwNtBLZd7ola8KwJg7EVjkpfhuvoAU2srI

{
    "product": "65f22d5e90e842d72d761629"
}

###
GET http://localhost:3000/orders/65e0d6037c9d3f7711d4c007
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzcwMjUxLCJleHAiOjE3MTAzNzM4NTF9.FLpTK9v5DCwNtBLZd7ola8KwJg7EVjkpfhuvoAU2srI

###
DELETE http://localhost:3000/orders/65e230491bea4cea9db748b5
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InJhbmRvbUBuZXQuY29tIiwidXNlcklEIjoiNjVlNzc1NTJiNGU2NDIwZjVkMDcyMTRjIiwiaWF0IjoxNzEwMzcwMjUxLCJleHAiOjE3MTAzNzM4NTF9.FLpTK9v5DCwNtBLZd7ola8KwJg7EVjkpfhuvoAU2srI


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "random@net.com",
    "password": "1234faba"
}

###
POST http://localhost:3000/user/login 
Content-Type: application/json

{
    "email": "random@net.com",
    "password": "1234faba"
}


###
POST http://localhost:3000/user/signup
Content-Type: application/json

{
    "email": "tester2@mail.com",
    "password": "abcdelgkj"
}

###
DELETE http://localhost:3000/user/65e77cca2c22b05d0ab07442
Content-Type: application/json